### PR TITLE
Making AllenAct pip-installable.

### PR DESCRIPTION
**Pull request by Lucaweihs**
In the interest of getting eyes on this large scale refactor, here is a draft of the new pip-installable AllenAct. Major changes:

1. `core` renamed to `allenact` (with it's own setup.py file, can be pip-installed with a command like `pip install -e "git+https://github.com/allenai/allenact.git@pip_installable#egg=allenact&subdirectory=allenact"`)
2. `plugins` renamed to `allenact_plugins` (with it's own setup.py file, can be pip installed with a command like `pip install -e "git+https://github.com/allenai/allenact.git@pip_installable#egg=allenact_plugins&subdirectory=allenact_plugins"`).
3. `utils` is now a submodule of `allenact`.
4. I created a new `allenact.embodiedai` directory that will contain implementations of general embodied-ai components (models, preprocessors, etc).
5. After pip-installing `allenact`, one can now run experiments using the `allenact` command. Try, for instance,
```bash
> # Get into a new virtual env
> pip install -e "git+https://github.com/allenai/allenact.git@pip_installable#egg=allenact&subdirectory=allenact"
> pip install -e "git+https://github.com/allenai/allenact.git@pip_installable#egg=allenact_plugins[minigrid]&subdirectory=allenact_plugins"
> allenact minigrid_tutorial -b projects/tutorials -m 8 -o minigrid_output -s 12345
```

Rather than looking over the file changes (basically everything has changed) I'd recommend looking at the [new file structure](https://github.com/allenai/allenact/tree/pip_installable) and perhaps the `setup.py` files (see `allenact/setup.py` and `allenact_plugins/setup.py`).

### CODE REVIEW

**Comment by jordis-ai2** [comment]
L *GREAT* TM. I just tried it and works well in my end.

**Review by jordis-ai2 — APPROVED** [review]

**Comment by mattdeitke** [comment]
I am getting errors both locally and on Colab when I try to pip install either. See:
https://colab.research.google.com/drive/1pq8iDQJf513mIeBoJmegxW026X3yVB7A?usp=sharing

```
Obtaining allenact from git+https://github.com/allenai/allenact.git@pip_installable#egg=allenact&subdirectory=allenact
  Cloning https://github.com/allenai/allenact.git (to revision pip_installable) to ./src/allenact
  Running command git clone -q https://github.com/allenai/allenact.git /content/src/allenact
  Running command git checkout -b pip_installable --track origin/pip_installable
  Switched to a new branch 'pip_installable'
  Branch 'pip_installable' set up to track remote branch 'pip_installable' from 'origin'.
ERROR: Files/directories not found in /content/src/allenact/allenact
```

**Comment by Lucaweihs** [comment]
I upgraded pip on Colab (`python -m pip install -U pip`) and the problem went away.

**Review by mattdeitke — APPROVED** [review]
👍 Yeah, works well! 

https://colab.research.google.com/drive/1pq8iDQJf513mIeBoJmegxW026X3yVB7A?usp=sharing

**Comment by jordis-ai2** [comment]
Just noticed the installation instructions are not up to date.

**Comment by jordis-ai2** [comment]
Just linked this to an old open issue (missing examples on how to use multiple agents/policies)

**Pull request merged**
