### PR TITLE
Switched to using a model trained on the full train set

### PR DESCRIPTION
**Pull request by klemenkotar**
I also updated the AWS link to contain the correct model

### CODE REVIEW

**Comment by jordis-ai2** [comment]
Sounds good. I would have also updated the part about visualization, but we can probably do that at a later point. (Maybe comment out the viz part of the tutorial until we can check that it works).

**Review by jordis-ai2 — COMMENTED** [review]
I'd either comment out the visualization part (make sure to also update the tutorial_index if you do so), or update the viz part of the tutorial to use a proper model checkpoint and perhaps an episode not in train. Other than that, LGTM.

**Comment by Lucaweihs** [comment]
@klemenkotar, I agree with Jordi, it would be great if you could have inference run on only the dev set so that people can actually run inference and look at the results quickly. We can point them to what needs to change if they want to run inference on everything.

**Comment by Lucaweihs** [comment]
Closing this as I believe we've since changed things so this PR is no longer needed. Let me know if this isn't the case.

**Pull request closed without merging**
