### PR TITLE
renaming player_screen_width/height to width/height; player_screen_wi…

### PR DESCRIPTION
**Pull request by ekolve**
player_screen_width and player_screen_height are deprecated parameters for the Controller in ai2thor.  This renames the params to width/height.

### CODE REVIEW

**Comment by Lucaweihs** [comment]
How backwards compatible are these changes? I.e. how far back can I go with AI2-THOR versions before giving `width=...` breaks as it expects `player_screen_width`?

**Comment by ekolve** [comment]
Okay, here is short history.  Prior to version 2.2.0, width/height had to be specified as arguments to the controller.start() method with the names player_screen_width/player_screen_height.  Starting with version 2.2.0, you could now pass in width/height (exact names were 'width', 'height') to the Controller constructor, but player_screen_width/player_screen_height were not accepted.  These parameters were passed through to the start() method.  So any code that used the pre-2.2.0 API worked fine (i.e. calling start(player_screen_width=X, player_screen_height=Y).  player_screen_width/player_screen_height have never been valid constructor params for any release.  At the end of the constructor of Controller is **unity_initialization_params which effectively swallows all the unmatched params and get used for the Initialize call into Unity.  I'm not sure I really like this because it has hidden this from us, but it makes it trivial to modify the Initialize code in csharp to accept a new parameter and for someone to start using really easy.

**Comment by Lucaweihs** [comment]
Ok gotcha. For backwards compatibility with people using the `IThorEnvironment` with kwargs, I think it would be safer to keep `player_screen_width` and `player_screen_height` as the arguments to the `IThorEnvironment` and only change 
```python
        def create_controller():
            return Controller(
                x_display=self.x_display,
                player_screen_width=self._start_player_screen_width,
                player_screen_height=self._start_player_screen_height,
                local_executable_path=self._local_thor_build,
                quality=self._quality,
            )
```
to
```python
        def create_controller():
            return Controller(
                x_display=self.x_display,
                width=self._start_player_screen_width,
                height=self._start_player_screen_height,
                local_executable_path=self._local_thor_build,
                quality=self._quality,
            )
```

**Comment by ekolve** [comment]
Reverted all the other name changes - leaving just the params to the Controller.

**Pull request merged**
